bin/ scripts indenting

diff --git a/bin/build-release b/bin/build-release
--- a/bin/build-release
+++ b/bin/build-release
@@ -64,9 +64,9 @@
 # shellcheck source=./share.sh source=./travis-share.sh
 _dir="$( dirname "$0" )"
 if [ -z "$TRAVIS" ]; then
-  source "${_dir}/share.sh"
+    source "${_dir}/share.sh"
 else
-  source "${_dir}/travis-share.sh"
+    source "${_dir}/travis-share.sh"
 fi
 unset _dir
 
@@ -77,158 +77,158 @@ CARGO_MANIFEST="${ROOT}/Cargo.toml"
 INCLUDE_FILES=()
 
 function include_file {
-  local filepath="${ROOT}/${1}"
-  if [ -f "$filepath" ]; then
-    INCLUDE_FILES+=("$filepath")
-  else
-    msg_strong "File to include in archive does not exist: $( colored "$COLOR_CODE" "$filepath" )"
-  fi
+    local filepath="${ROOT}/${1}"
+    if [ -f "$filepath" ]; then
+        INCLUDE_FILES+=("$filepath")
+    else
+        msg_strong "File to include in archive does not exist: $( colored "$COLOR_CODE" "$filepath" )"
+    fi
 }
 
 function exclude_file {
-  local filepath_remove=("${ROOT}/${1}")
-  INCLUDE_FILES=("${INCLUDE_FILES[@]/$filepath_remove}")
+    local filepath_remove=("${ROOT}/${1}")
+    INCLUDE_FILES=("${INCLUDE_FILES[@]/$filepath_remove}")
 }
 
 include_file "README.md"
 include_file "LICENSE"
 
 function get_latest_version {
-  check "sed"
-  shopt -s nullglob
-  [ -d "$RELEASE_DIR" ] || err "Directory '$RELEASE_DIR' doesn't exist."
-  local highest=0
-  local vers
-  local vers_num
-  local highest_num
-  local file
-  local new_vers
+    check "sed"
+    shopt -s nullglob
+    [ -d "$RELEASE_DIR" ] || err "Directory '$RELEASE_DIR' doesn't exist."
+    local highest=0
+    local vers
+    local vers_num
+    local highest_num
+    local file
+    local new_vers
 
-  for file in "$RELEASE_DIR"/*.zip; do
-    vers="$( echo "$file" | grep -Eo '([0-9]\.?)+\.zip' | sed 's/\.zip//' )"
-    if [ -n "$vers" ]; then
-      vers_num="${vers//./}"
-      highest_num="${highest//./}"
-      [ $vers_num -gt $highest_num ] && highest="$vers"
-    fi
-  done
+    for file in "$RELEASE_DIR"/*.zip; do
+        vers="$( echo "$file" | grep -Eo '([0-9]\.?)+\.zip' | sed 's/\.zip//' )"
+        if [ -n "$vers" ]; then
+            vers_num="${vers//./}"
+            highest_num="${highest//./}"
+            [ $vers_num -gt $highest_num ] && highest="$vers"
+        fi
+    done
 
-  new_vers="$( echo "$highest" | sed -E 's/(.*)([0-9]+)$/echo "\1$((\2+1))"/e' )"
-  echo "$new_vers"
+    new_vers="$( echo "$highest" | sed -E 's/(.*)([0-9]+)$/echo "\1$((\2+1))"/e' )"
+    echo "$new_vers"
 }
 
 function get_version_from_cargo {
-  check "grep"
-  check "cut"
-  check "tr"
+    check "grep"
+    check "cut"
+    check "tr"
 
-  check_file "$CARGO_MANIFEST"
+    check_file "$CARGO_MANIFEST"
 
-  local version
-  if ! version="$(
-    grep -Eom1 '^\s*version\s*=\s*.+$' "$CARGO_MANIFEST" \
-      | cut -d'=' -f2 \
-      | tr -d ' "'
-  )"; then
-    echo "ERROR"
-    err "Error getting current crate version from file '${CARGO_MANIFEST}'"
-  fi
+    local version
+    if ! version="$(
+        grep -Eom1 '^\s*version\s*=\s*.+$' "$CARGO_MANIFEST" \
+            | cut -d'=' -f2 \
+            | tr -d ' "'
+    )"; then
+        echo "ERROR"
+        err "Error getting current crate version from file '${CARGO_MANIFEST}'"
+    fi
 
-  echo "$version"
+    echo "$version"
 }
 
 function get_filename_for_target {
-  local target="$1"
-  [ -z "$target" ] && err "No target name given to function \`$0\`."
-  echo "${RELEASE_FILE_PREFIX}${target}${RELEASE_FILE_SUFFIX}-${RELEASE_VERSION}"
+    local target="$1"
+    [ -z "$target" ] && err "No target name given to function \`$0\`."
+    echo "${RELEASE_FILE_PREFIX}${target}${RELEASE_FILE_SUFFIX}-${RELEASE_VERSION}"
 }
 
 function mk_archive {
-  local path="$1"
-  local dir
-  local filename
-  local zipname
-  [ -z "$1" ] && err "No path given to function \`$0\`."
-  check "zip" && check "dirname" && check "basename"
-  dir="$( dirname "$path" )"
-  pushd "$dir"
-  filename="$( basename "$path" )"
-  zipname="${RELEASE_ZIP_PREFIX}${filename}${RELEASE_ZIP_SUFFIX}.zip"
-  prev_spacing="$spacing"
-  spacing="$spacing  "
-  msg "${prev_spacing}Zipping directory..."
-  if [ -f "$zipname" ]; then
-    msg "${spacing}zip archive already exists: $( colored "$COLOR_CODE" "$zipname" )"
-    msg "${spacing}Deleting existing zip archive and creating new zip"
-  fi
-  try_run "zip -r $zipname $filename"
-  try_run "rm -rf $filename"
-  spacing="$prev_spacing"
-  popd
+    local path="$1"
+    local dir
+    local filename
+    local zipname
+    [ -z "$1" ] && err "No path given to function \`$0\`."
+    check "zip" && check "dirname" && check "basename"
+    dir="$( dirname "$path" )"
+    pushd "$dir"
+    filename="$( basename "$path" )"
+    zipname="${RELEASE_ZIP_PREFIX}${filename}${RELEASE_ZIP_SUFFIX}.zip"
+    prev_spacing="$spacing"
+    spacing="$spacing  "
+    msg "${prev_spacing}Zipping directory..."
+    if [ -f "$zipname" ]; then
+        msg "${spacing}zip archive already exists: $( colored "$COLOR_CODE" "$zipname" )"
+        msg "${spacing}Deleting existing zip archive and creating new zip"
+    fi
+    try_run "zip -r $zipname $filename"
+    try_run "rm -rf $filename"
+    spacing="$prev_spacing"
+    popd
 }
 
 function run {
-  check "cargo"
-  local target_display
-  local filename
-  local target
-  local spacing
+    check "cargo"
+    local target_display
+    local filename
+    local target
+    local spacing
 
-  case "$RELEASE_VERSION" in
-    "auto")
-      RELEASE_VERSION="$( get_latest_version )"
-      ;;
-    "cargo")
-      RELEASE_VERSION="$( get_version_from_cargo )"
-      ;;
-  esac
-
-  msg_strong "Building release version $( colored "$COLOR_CODE" "$RELEASE_VERSION" )"
-
-  for target in "${RELEASE_TARGETS[@]}"; do
-    spacing_strong="  "
-    target_display="$( colored "$COLOR_CODE" "$target" )"
-    msg_strong "${spacing_strong}Building release for $target_display"
-    filename="$( get_filename_for_target "$target" )"
-    spacing="${spacing_strong}${spacing_strong}"
-
-    case "$target" in
-      "linux" | "osx" | "default")
-        local RUST_TARGET_DIR="${ROOT}/target/release"
-        RELEASE_EXE_NAME="${RELEASE_EXE_NAME/.exe/}"
-        RELEASE_EXE_NAME_OUTPUT="${RELEASE_EXE_NAME_OUTPUT/.exe/}"
-        include_file "${RELEASE_DESKTOP_NAME}"
-
-        build_release "$@"
-        ;;
-
-      "windows")
-        local RUST_TARGET_DIR=
-        local maybe_target=
-        if [ -n "$TRAVIS" ]; then
-          # Use default rust target path when run from travis (is windows OS on travis)
-          RUST_TARGET_DIR="${ROOT}/target/release"
-          maybe_target=
-        else
-          # Use non-default rust target path when cross-compiling
-          RUST_TARGET_DIR="${ROOT}/target/${WINDOWS_TARGET}/release"
-          maybe_target="--target $WINDOWS_TARGET"
-        fi
-        RELEASE_EXE_NAME="${RELEASE_EXE_NAME/.exe/}.exe"
-        RELEASE_EXE_NAME_OUTPUT="${RELEASE_EXE_NAME_OUTPUT/.exe/}.exe"
-        exclude_file "${RELEASE_DESKTOP_NAME}"
-        [[ "$RELEASE_FEATURES" =~ "controller" ]] && include_file "SDL2.dll"
-
-        build_release "$@" $maybe_target
-        ;;
-
-      *)
-        err "Target '$target_display' is not valid"
-        ;;
+    case "$RELEASE_VERSION" in
+        "auto")
+            RELEASE_VERSION="$( get_latest_version )"
+            ;;
+        "cargo")
+            RELEASE_VERSION="$( get_version_from_cargo )"
+            ;;
     esac
 
-    msg_strong "${spacing_strong}Created release for ${target_display}\n${spacing_strong}$( colored "$COLOR_CODE" "${RELEASE_DIR}/${filename}.zip" )"
-  done
+    msg_strong "Building release version $( colored "$COLOR_CODE" "$RELEASE_VERSION" )"
+
+    for target in "${RELEASE_TARGETS[@]}"; do
+        spacing_strong="  "
+        target_display="$( colored "$COLOR_CODE" "$target" )"
+        msg_strong "${spacing_strong}Building release for $target_display"
+        filename="$( get_filename_for_target "$target" )"
+        spacing="${spacing_strong}${spacing_strong}"
+
+        case "$target" in
+            "linux" | "osx" | "default")
+                local RUST_TARGET_DIR="${ROOT}/target/release"
+                RELEASE_EXE_NAME="${RELEASE_EXE_NAME/.exe/}"
+                RELEASE_EXE_NAME_OUTPUT="${RELEASE_EXE_NAME_OUTPUT/.exe/}"
+                include_file "${RELEASE_DESKTOP_NAME}"
+
+                build_release "$@"
+                ;;
+
+            "windows")
+                local RUST_TARGET_DIR=
+                local maybe_target=
+                if [ -n "$TRAVIS" ]; then
+                    # Use default rust target path when run from travis (is windows OS on travis)
+                    RUST_TARGET_DIR="${ROOT}/target/release"
+                    maybe_target=
+                else
+                    # Use non-default rust target path when cross-compiling
+                    RUST_TARGET_DIR="${ROOT}/target/${WINDOWS_TARGET}/release"
+                    maybe_target="--target $WINDOWS_TARGET"
+                fi
+                RELEASE_EXE_NAME="${RELEASE_EXE_NAME/.exe/}.exe"
+                RELEASE_EXE_NAME_OUTPUT="${RELEASE_EXE_NAME_OUTPUT/.exe/}.exe"
+                exclude_file "${RELEASE_DESKTOP_NAME}"
+                [[ "$RELEASE_FEATURES" =~ "controller" ]] && include_file "SDL2.dll"
+
+                build_release "$@" $maybe_target
+                ;;
+
+            *)
+                err "Target '$target_display' is not valid"
+                ;;
+        esac
+
+        msg_strong "${spacing_strong}Created release for ${target_display}\n${spacing_strong}$( colored "$COLOR_CODE" "${RELEASE_DIR}/${filename}.zip" )"
+    done
 }
 
 # Pre-set local variables:
@@ -237,34 +237,34 @@ function run {
 #   local target
 #   local spacing
 function build_release {
-  local features_arg=""
-  [ -n "$RELEASE_FEATURES" ] && features_arg="--features ${RELEASE_FEATURES}"
-  local prev_spacing="$spacing"
-  spacing="$spacing  "
-  msg "${prev_spacing}Compiling..."
-  also_to_stderr="$RELEASE_PRINT_CARGO_STDERR" try_run \
-    "cargo +${RELEASE_RUST_VERSION} build --release ${features_arg} $*"
+    local features_arg=""
+    [ -n "$RELEASE_FEATURES" ] && features_arg="--features ${RELEASE_FEATURES}"
+    local prev_spacing="$spacing"
+    spacing="$spacing  "
+    msg "${prev_spacing}Compiling..."
+    also_to_stderr="$RELEASE_PRINT_CARGO_STDERR" try_run \
+        "cargo +${RELEASE_RUST_VERSION} build --release ${features_arg} $*"
 
-  local target_dir="${RELEASE_DIR}/${filename}"
-  mkdir "$target_dir"
+    local target_dir="${RELEASE_DIR}/${filename}"
+    mkdir "$target_dir"
 
-  msg "${prev_spacing}Copying executable and resources..."
-  try_run "cp ${RUST_TARGET_DIR}/${RELEASE_EXE_NAME} ${target_dir}/${RELEASE_EXE_NAME_OUTPUT}"
-  try_run "cp -r $RELEASE_RESOURCES_DIR $target_dir"
-  try_run "cp ${INCLUDE_FILES[*]} $target_dir";
-  spacing="$prev_spacing"
+    msg "${prev_spacing}Copying executable and resources..."
+    try_run "cp ${RUST_TARGET_DIR}/${RELEASE_EXE_NAME} ${target_dir}/${RELEASE_EXE_NAME_OUTPUT}"
+    try_run "cp -r $RELEASE_RESOURCES_DIR $target_dir"
+    try_run "cp ${INCLUDE_FILES[*]} $target_dir";
+    spacing="$prev_spacing"
 
-  mk_archive "$target_dir"
+    mk_archive "$target_dir"
 
-  # If this script was run from travis,
-  # write the filepath of the generated zip to a file.
-  # (used by bin/travis-upload-atrifact script)
-  if [ -n "$TRAVIS" ]; then
-    local file_with_path="${ROOT}/.travis-release-path-${target}"
-    local zip_path
-    zip_path="$( dirname "$target_dir" )/${RELEASE_ZIP_PREFIX}$( basename "$target_dir" )${RELEASE_ZIP_SUFFIX}.zip"
-    echo -n "$zip_path" > "$file_with_path"
-  fi
+    # If this script was run from travis,
+    # write the filepath of the generated zip to a file.
+    # (used by bin/travis-upload-atrifact script)
+    if [ -n "$TRAVIS" ]; then
+        local file_with_path="${ROOT}/.travis-release-path-${target}"
+        local zip_path
+        zip_path="$( dirname "$target_dir" )/${RELEASE_ZIP_PREFIX}$( basename "$target_dir" )${RELEASE_ZIP_SUFFIX}.zip"
+        echo -n "$zip_path" > "$file_with_path"
+    fi
 }
 
 # Set global settings variables.
